### ISSUE TITLE
"Unable to get the token"

### ISSUE THREAD

**Issue by unfairDude** [Adam0005/Fake-Verification-Bot#1]
As title say, I get error
Unable to get token

**Comment by Adam0005** [comment]
Like you don't get the token of your victims?

**Comment by unfairDude** [comment]
![IMG_20230107_005012.jpg](https://user-images.githubusercontent.com/102629559/211142382-e1ad26c2-bdd4-47b6-b418-f8a4efe690e8.jpg)

I get this

**Comment by TheCuteOwl** [comment]
Same here

**Comment by giiovi** [comment]
Feel it!
